import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { FOOTER_HEIGHT, HEADER_HEIGHT } from '@/helpers/constants'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <body>
          <div
            className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen antialiased`}
            style={{
              gridTemplateRows: `${HEADER_HEIGHT} 1fr ${FOOTER_HEIGHT}`,
            }}
          >
            <div
              className={`bg-slate-500`}
              style={{ height: `${HEADER_HEIGHT}` }}
            >
              headers go here {`${HEADER_HEIGHT}`}
            </div>
            <div>{children}</div>
            <div
              className="bg-slate-500"
              style={{ height: `${FOOTER_HEIGHT}` }}
            >
              footers go here
            </div>
          </div>
        </body>
      </body>
    </html>
  )
}
